import type { Metadata } from "next";

import "./globals.css";
import { ReactNode } from "react";

import Header from "./components/Header";
import Footer from "./components/Footer";
import { UserProvider } from "./context/UserContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" >
      <body>
        <UserProvider>

          <Header />
          <main>{children}</main>
          <Footer />

        </UserProvider>
      </body>
    </html>
  )
};